<a href="https://colab.research.google.com/github/Popen-23/belajar-git/blob/master/intro_to_google_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a = 10
print(a)


10


In [10]:
b = 15
b

15

# Shell Commands

In [14]:
!ls

sample_data


Magics

In [17]:
import numpy as np
%timeit np.linalg.eigvals(np.random.rand(100, 100))

9.04 ms ± 66.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
%%html
<marquee style='width30%; color: green;'>Hello World!</marquee>

Documentation

In [22]:
np.random?

# Markdown

**Python** *Programming*

[Google Website](https://google.com)

#Numpy

In [ ]:
import numpy as np


Array dengan rank 1 dan panjang 3.

In [23]:
[1, 2, 3]

[1, 2, 3]

Array dengan rank 2 dan panjang 3.

In [24]:
([1, 2, 3], [4, 5, 6])

([1, 2, 3], [4, 5, 6])

In [26]:
a = np.array([1, 2, 3])
b = np.array([(1, 2, 3), (4, 5, 6)])

print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


**ndarray**: nama class untuk sebuah numpy array

#Properties yg terdapat di dalam ndarray
* ndarray.ndim: mengembalikan dimensi dari numpy array
* ndarray.shape: mereturn baris & colum dari sebuah numpy array
* ndarray.size : mengetahui jumlah element di dalam numpy array
* nd array.dtype: mencari tipe data di dalam numpy array
* ndarray.itemsize: mengetahui ukuran element (bytes) yg ad di numpy array
*nd array:data: buffer untuk menyimpan element-element di dalam numpy array


In [ ]:
a = np.array([1, 2, 3])
b = np.array([(1, 2, 3), (4, 5, 6)])

In [29]:
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)

2
(2, 3)
6
int64
8


Create Numpy array

* np.zeros: Untuk membuat numpy array yg yg semua isinya adalah nol
* np.ones: Untuk membuat numpy array yang semua isinya adalah 1
* np.arrange: untuk berikan scope dan panjang dari step
* np.linspace: untuk berikan scope dan jumlah element yang kita inginkan
*np.random.random: memberikan angka acak



In [31]:
np.zeros((3, 3)) # kurung pertama untuk pemanggilan method yg ke2 utk parameternya

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.ones((3, 3)) # artinya 3row dan 3 colum sama seperti d atas

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.arange(1, 2, 0.2) # ([start],stop,[step])artinya angka 1 - 2 bakal di generate berdasarkan selisih angka 0,2

array([1. , 1.2, 1.4, 1.6, 1.8])

In [38]:
np.linspace(1, 3, 6) # ([start],stop,[jumlah element]) artinya angka 1-3 di generate brdsarkan jumlah element=> 6

array([1. , 1.4, 1.8, 2.2, 2.6, 3. ])

In [39]:
np.random.random((2,3))

array([[0.57096413, 0.41671074, 0.24975721],
       [0.82688723, 0.24597545, 0.12732385]])

# Shape and Operation

* reshape: Mengubah dimensi/shape dari sebuah numpy array.
* vstack: untuk merge numpy array secara vertical.
* hstack: untuk merge numpy array secara horizontal.
* vsplit: untuk split numpy array secara vertical.
* hsplit: untuk split numpy array  secara horizontal.

In [49]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)

[[1 2 3]
 [4 5 6]]


In [41]:
a = a.reshape(3, -1) # dengan cara masukan angka -1 maka akan otomatis me reshape tanpa menentukan jumlah rownya
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [43]:
b = np.array([(7, 8), (9, 10)])
print(b)

[[ 7  8]
 [ 9 10]]


In [44]:
np.vstack((a, b)) # menggabungkan variable a & b secara vertical

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [45]:
c = np.array([(11, 12, 13), (14, 15, 16)])
c

array([[11, 12, 13],
       [14, 15, 16]])

In [50]:
d = np.hstack((a, c)) # menggabungkan variable a & c secara horizontal
d

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [54]:
np.vsplit(d, 2)

[array([[ 1,  2,  3, 11, 12, 13]]), array([[ 4,  5,  6, 14, 15, 16]])]

In [52]:
np.hsplit(d, 3)

[array([[1, 2],
        [4, 5]]), array([[ 3, 11],
        [ 6, 14]]), array([[12, 13],
        [15, 16]])]